packetbeat.interfaces.device: any #SEGUNDO CAMBIO
packetbeat.interfaces.snaplen: 1514
packetbeat.interfaces.type: af_packet
packetbeat.interfaces.buffer_size_mb: 100
packetbeat.ignore_outgoing: false

packetbeat.flows:
  # Enable Network flows. Default: true
  #enabled: true

  # Set network flow timeout. Flow is killed if no packet is received before being
  # timed out.
  timeout: 30s

  # Configure reporting period. If set to -1, only killed flows will be reported
  period: 10s

packetbeat.protocols:
- type: http
  ports: [80]

output.logstash:
  hosts: ["logstash:5042"]