filebeat.config:
  modules:
    path: ${path.config}/log/*.log
    reload.enabled: true

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /log/*.log

output.logstash:

  hosts: ["logstash:5047"]

